CREATE DATABASE IF NOT EXISTS dwh;
USE dwh;

DROP TABLE IF EXISTS neo4j_log;

CREATE TABLE neo4j_log (
  ID        INT      NOT NULL AUTO_INCREMENT,
  OPERATION VARCHAR(10),
  OMDBIDB   VARCHAR(10),
  TYPE      VARCHAR(10),
  DATE      DATETIME NOT NULL,
  PRIMARY KEY (ID)
);