CREATE DATABASE IF NOT EXISTS dwh;
USE dwh;

DROP TABLE IF EXISTS neo4j_log;

CREATE TABLE neo4j_log (
  ID        INT      NOT NULL AUTO_INCREMENT,
  OPERATION VARCHAR(10),
  OMDBID    VARCHAR(10),
  TYPE      VARCHAR(10),
  DATE      DATETIME NOT NULL,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS user_ratings;

CREATE TABLE user_ratings (
  ID     INT      NOT NULL AUTO_INCREMENT,
  USER   VARCHAR(25),
  OMDBID VARCHAR(10),
  RATING INT,
  DATE   DATETIME NOT NULL,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS user_viewing_history;

CREATE TABLE user_viewing_history (
  ID     INT      NOT NULL AUTO_INCREMENT,
  USER   VARCHAR(25),
  OMDBID VARCHAR(10),
  DATE   DATETIME NOT NULL,
  PRIMARY KEY (ID)
);